### ISSUE TITLE
Live Demo, and some small typo 

### ISSUE THREAD

**Issue by OsDroidi** [alexeagleson/react-dark-mode#1]
I would first thank you for this great tutorial, I was really struggling and tried different methods but nothing seem to really work.

while I was reading I found this small issues, and I hope this can help improve this great work. 

1- in the [Live demo](https://github.com/alexeagleson/react-dark-mode#live-demo) chapter it just shows this weird text.
```
{% codesandbox dry-meadow-64786%}
```

2- in the [Prerequisites](https://github.com/alexeagleson/react-dark-mode#prerequisites) chapter  in the last two paragraph there is an extra e.

 ```diff
 - , thee amount of explicit typing in these examples is minimal.
 + , the amount of explicit typing in these examples is minimal.
 ```
 
 3- [Adding Styles](https://github.com/alexeagleson/react-dark-mode#adding-styles) chapter in the first step "will" is duplicated.
 
 ```diff
 - This is where will will create the CSS variables that hold the colours for our light theme.
 + This is where will create the CSS variables that hold the colours for our light theme.
 ```

**Comment by alexeagleson** [comment]
That helps a lot, thank you!  I have committed the tutorial errors

The codesandbox text is embedded markdown that doesn't render on Github, but does render on the original blog post this repository is created for on dev.to (linked below):

https://dev.to/alexeagleson/how-to-create-a-dark-mode-component-in-react-3ibg
